version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/app
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=admin
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
